### ISSUE TITLE
[Bug] exception handling throws error regarding the Logger

### ISSUE THREAD

**Issue by CyberDev01** [exislow/tidal-dl-ng#100]
### What happened?

I tried downloading the following track:

Jai Wolf - Moon Rider (feat. Wrabel)
https://listen.tidal.com/album/127568671/track/127568672

While downloading, at 6% the following error occured regarding the logger of the program.
(I exchanged my personal token with <my-token>)

Thank you for your work!

### Version App

v0.13.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/download.py", line 145, in _download
    r.raise_for_status()
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://sp-ad-fa.audio.tidal.com/mediatracks/GikSJzk0ZWU3NWQ2OGRmODM1MzZmZGYzNTBiMDljYTBiY2Q3XzYyLm1wNCIgHQAAgEAgAioQP6nTQmorIAPV5ZXNMGiAZTIFDQAAoEE/3.mp4?token=<my-token>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/gui.py", line 807, in watcher_queue_download
    result = self.on_queue_download(media, quality=quality)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/gui.py", line 848, in on_queue_download
    result = self.download(item_media, self.dl, delay_track=download_delay, quality=quality)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/gui.py", line 877, in download
    result_dl, path_file = dl.item(
                           ^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/download.py", line 264, in item
    tmp_path_file = self._download(media=media, path_file=tmp_path_file)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/download.py", line 158, in _download
    self.fn_logger(e)
TypeError: 'Logger' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/worker.py", line 31, in run
    self.fn(*self.args, **self.kwargs)
  File "/home/eric/.pyenv/versions/3.11.8/envs/tidal-dl-ng/lib/python3.11/site-packages/tidal_dl_ng/gui.py", line 813, in watcher_queue_download
    except e:
           ^
NameError: name 'e' is not defined
```

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "/home/eric/Musik", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "{album_artist}/{album_title}/{track_volume_num}{album_track_num} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "{album_artist}/{album_title}/{album_track_num} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}", "video_convert_mp4": true, "path_binary_ffmpeg": "/usr/bin/ffmpeg", "metadata_cover_dimension": "1280", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
Thank you. It is already fixed in master with https://github.com/exislow/tidal-dl-ng/commit/07e5366193fc229886cc77f9b796e8db76934cf6 and will be released soon.
