### ISSUE TITLE
[Bug] Can't start the downloader on a headless linux server

### ISSUE THREAD

**Issue by DW4y** [exislow/tidal-dl-ng#115]
### What happened?

Hello, I installed the package from pip and got an error message when using tidal-dl-ng --help.

### Version App

latest

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/pierre/.local/bin/tidal-dl-ng", line 5, in <module>
    from tidal_dl_ng.cli import app
  File "/home/pierre/.local/lib/python3.10/site-packages/tidal_dl_ng/__init__.py", line 10, in <module>
    from tidal_dl_ng.constants import REQUESTS_TIMEOUT_SEC
  File "/home/pierre/.local/lib/python3.10/site-packages/tidal_dl_ng/constants.py", line 1, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.10/enum.py)
```

### Your settings

```json
No tidal_dl_ng folder in .config
```

**Comment by exislow** [comment]
Please read the requirements, especially regarding Python.: https://github.com/exislow/tidal-dl-ng?tab=readme-ov-file#-installation--upgrade
