### ISSUE TITLE
[Help] Authentication Error 

### ISSUE THREAD

**Issue by kevin26exe** [exislow/tidal-dl-ng#185]
### I need Help.

Hi team,

I tried opening tidal dl ng and I am getting error below.

`Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 1042, in <module>
  File "tidal_dl_ng\gui.py", line 1033, in gui_activate
  File "tidal_dl_ng\gui.py", line 117, in __init__
  File "tidal_dl_ng\gui.py", line 128, in init_tidal
  File "tidal_dl_ng\helper\decorator.py", line 19, in __call__
  File "tidal_dl_ng\config.py", line 101, in __init__
  File "tidal_dl_ng\config.py", line 127, in login_token
  File "tidalapi\session.py", line 403, in load_oauth_session
  File "tidalapi\request.py", line 139, in request
  File "tidalapi\request.py", line 110, in basic_request
  File "tidalapi\session.py", line 727, in token_refresh
tidalapi.exceptions.AuthenticationError: Authentication failed
`

Kindly asking if anyone has an idea on how to fix?
Appreciate the help!

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
Apologies but I am not able to locate %HOMEPATH%\.config\tidal_dl_ng\settings.json.
```

**Comment by MasterRahool** [comment]
also getting this error out of nowhere after it worked no problem for weeks, redownloaded and same error popping up

**Comment by kevin26exe** [comment]
Resolved by deleting token.json.
In orrder to delete, go to run ->  %HOMEPATH%\.config\tidal_dl_ng\ -> delete token.json

**Comment by MasterRahool** [comment]
thank you! Had a similar issue and that fixed it
