### ISSUE TITLE
[Help] Authentication failed

### ISSUE THREAD

**Issue by duckifi** [exislow/tidal-dl-ng#199]
### I need Help.

The program used to work flawlessly until my tidal subsciption expired. Now every time I run the program it just says "Failed to execute script 'gui' due to unhandled exception: Authentication failed"

```
Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 1042, in <module>
  File "tidal_dl_ng\gui.py", line 1033, in gui_activate
  File "tidal_dl_ng\gui.py", line 117, in __init__
  File "tidal_dl_ng\gui.py", line 128, in init_tidal
  File "tidal_dl_ng\helper\decorator.py", line 19, in __call__
  File "tidal_dl_ng\config.py", line 101, in __init__
  File "tidal_dl_ng\config.py", line 127, in login_token
  File "tidalapi\session.py", line 403, in load_oauth_session
  File "tidalapi\request.py", line 139, in request
  File "tidalapi\request.py", line 110, in basic_request
  File "tidalapi\session.py", line 727, in token_refresh
tidalapi.exceptions.AuthenticationError: Authentication failed
```

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
sorry i cant seem to find it
```

**Comment by shivamzala** [comment]
+1

**Comment by loddar66** [comment]
![image](https://github.com/user-attachments/assets/fe5a9d8b-ec33-43cd-94ba-8bb2164a5cb3)

as you stated: "subscription expired" - the program is not supposed to work without a paid plan (see requirements) ...

**Comment by duckifi** [comment]
would i be able to sign out of my current account without executing the program? because the error occurs right after i execute it.

**Comment by duckifi** [comment]
would i be able to sign out of my current account without executing the program? because the error occurs right after i execute it.

**Comment by duckifi** [comment]
would i be able to sign out of my current account without executing the program? because the error occurs right after i execute it.

**Comment by exislow** [comment]
Just delete `~/.config/tidal_dl_ng/token.json` (macOS & Linux) / `%HOMEPATH%\.config\tidal_dl_ng\token.json`
