### ISSUE TITLE
[Bug] "Unhandled exception in script"

### ISSUE THREAD

**Issue by dendenbgc** [exislow/tidal-dl-ng#208]
### What happened?

when I try to open it says "Failed to execute script 'gui' due to unhandled exception: Authentication failed

I have no idea how to code. I just download and run it.
It has worked for me previously and suddenly no longer works

### Version App

most recent version

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 1042, in <module>
  File "tidal_dl_ng\gui.py", line 1033, in gui_activate
  File "tidal_dl_ng\gui.py", line 117, in __init__
  File "tidal_dl_ng\gui.py", line 128, in init_tidal
  File "tidal_dl_ng\helper\decorator.py", line 19, in __call__
  File "tidal_dl_ng\config.py", line 101, in __init__
  File "tidal_dl_ng\config.py", line 127, in login_token
  File "tidalapi\session.py", line 403, in load_oauth_session
  File "tidalapi\request.py", line 139, in request
  File "tidalapi\request.py", line 110, in basic_request
  File "tidalapi\session.py", line 727, in token_refresh
tidalapi.exceptions.AuthenticationError: Authentication failed
```

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": false, "lyrics_file": false, "video_download": false, "download_delay": true, "download_base_path": "~/download", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "1280", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by MeloleM** [comment]
this is prolly cause the token is old/expired.
navigate to `%HOMEPATH%\.config\tidal_dl_ng\` (open run and place that in there) and delete token.json, then log in again
