### ISSUE TITLE
Error trying to start program.

### ISSUE THREAD

**Issue by Heisandent** [exislow/tidal-dl-ng#23]
Getting the below error as are others here starting the program:

Failed to execute script 'gui' due to unhandled exception: cannot access local variable 'settings_json' where it is not associated with a value.

Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 535, in <module>
  File "tidal_dl_ng\gui.py", line 528, in gui_activate
  File "tidal_dl_ng\gui.py", line 64, in __init__
  File "tidal_dl_ng\helper\decorator.py", line 19, in __call__
  File "tidal_dl_ng\config.py", line 77, in __init__
  File "tidal_dl_ng\config.py", line 66, in read
UnboundLocalError: cannot access local variable 'settings_json' where it is not associated with a value

Using windows 10 pro 64

**Comment by exislow** [comment]
Thank you for your report. Duplicates #20.
