### ISSUE TITLE
[Bug]  Error calling Python override with  "worker.py" and 

### ISSUE THREAD

**Issue by Paloik** [exislow/tidal-dl-ng#251]
### What happened?

I get some error-messages in the commandline when i'm using tdng GUI related to the "working.py" file.
How will i notice whether a simultaneous download is performed? At the moment I would say that the program does not perform simultaneous downloads.

### Version App

v0.20.3

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error calling Python override of QRunnable::run(): Traceback (most recent call last):
  File "/home/basti/.local/lib/python3.12/site-packages/tidal_dl_ng/worker.py", line 31, in run
    self.fn(*self.args, **self.kwargs)
  File "/home/basti/.local/lib/python3.12/site-packages/tidal_dl_ng/gui.py", line 913, in watcher_queue_download
    items: [QtWidgets.QTreeWidgetItem | None] = self.tr_queue_download.findItems(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal C++ object (PySide6.QtWidgets.QTreeWidget) already deleted.
```

### Your settings

```json
{
    "skip_existing": true,
    "lyrics_embed": true,
    "lyrics_file": false,
    "video_download": false,
    "download_delay": true,
    "download_base_path": "/media/basti/Daten/Music",
    "quality_audio": "LOSSLESS",
    "quality_video": "720",
    "format_album": "Albums/{album_artist}/{album_year} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": false,
    "path_binary_ffmpeg": "",
    "metadata_cover_dimension": "320",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": false,
    "downloads_simultaneous_per_track_max": 20
}
```

**Comment by exislow** [comment]
Stale
