### ISSUE TITLE
[Bug] No module named 'PySide6' when running gui

### ISSUE THREAD

**Issue by ramonskie** [exislow/tidal-dl-ng#298]
### What happened?

when trying to run `tidal-dl-ng-gui` or `tidal-dl-ng gui` i get the error that its missing `PySide6`
this happens on a clean install on a clean python 3.12 environment installed with pyenv.

it seems to me that the `PySide6` is not properly added in the requirements file
and will only install it for development.

the suggestion was to  `pip install pyside6 pyqtdarktheme`
and i got
```
Traceback (most recent call last):
  File "/home/ramonskie/.pyenv/versions/3.12.3/bin/tidal-dl-ng-gui", line 8, in <module>
    sys.exit(gui_activate())
             ^^^^^^^^^^^^^^
  File "/home/ramonskie/.pyenv/versions/3.12.3/lib/python3.12/site-packages/tidal_dl_ng/gui.py", line 1072, in gui_activate
    qdarktheme.enable_hi_dpi()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'qdarktheme' has no attribute 'enable_hi_dpi'
````

this was then again solved by using `pip install pyqtdarktheme-fork`

### Version App

0.23.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/ramonskie/.pyenv/versions/3.12.3/bin/tidal-dl-ng-gui", line 5, in <module>
    from tidal_dl_ng.gui import gui_activate
  File "/home/ramonskie/.pyenv/versions/3.12.3/lib/python3.12/site-packages/tidal_dl_ng/gui.py", line 10, in <module>
    from tidal_dl_ng.dialog import DialogLogin, DialogPreferences, DialogVersion
  File "/home/ramonskie/.pyenv/versions/3.12.3/lib/python3.12/site-packages/tidal_dl_ng/dialog.py", line 8, in <module>
    from PySide6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PySide6'
```

### Your settings

```json
default
```

**Comment by exislow** [comment]
Since you have ignored all directions in the issue template, while creating this issue, and did not provide any information how to reproduce this, I will just close this issue.

I also assume you did not read the readme how to install this app correctly.

**Comment by ramonskie** [comment]
wow rude...
i assume that you havent even took the time to read the issue as it explains the whole debug process..

but hey good luck with your project. i won't take my time to contribute to this.

**Comment by exislow** [comment]
So, you do not consider your behavior rude, despite you ignore clear directions given on how to create bug reports, but instead you like to steal my time? Wow... 

![Screenshot 2025-01-03 at 14 11 23](https://github.com/user-attachments/assets/a6da7b9e-7691-474a-a0a9-29ab993b4d93)


Anyway... Thanks a lot. All the best to you. I am sure your time is better spent somewhere else.

**Comment by ramonskie** [comment]
i filled in this template.
and edited the issue 15 min later when i found a resolution.
