### ISSUE TITLE
[Bug]  some album download leads to TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by CyberDev01** [exislow/tidal-dl-ng#54]
### What happened?

First of all: 
Thanks and keep up the good work!

Unfortunately, I am experiencing the following error:

When downloading an album, the following error sometimes occurs (see log output):
"TypeError: 'NoneType' object is not iterable"

Example:
Frankie Goes To Hollywood - Welcome To The Pleasuredome (album_id: 86639807)

As soon as the first track has reached 100%, the said error is displayed, but it is not always the first track, e.g. with the album (Schiller - Zeitreise - Das Beste von Schiller) the error occurs after the fourth track.

### Version

v0.8.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/worker.py", line 31, in run
    self.fn(*self.args, **self.kwargs)
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/gui.py", line 521, in on_download_results
    self.download(media, self.dl, delay_track=download_delay)
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/gui.py", line 535, in download
    dl.items(
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/download.py", line 382, in items
    status_download, result_path_file = self.item(
                                        ^^^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/download.py", line 233, in item
    tmp_path_file = self._download(media=media, stream_manifest=stream_manifest, path_file=tmp_path_file)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/download.py", line 153, in _download
    self.metadata_write(media, tmp_path_file_decrypted)
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/download.py", line 328, in metadata_write
    m.save()
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/metadata.py", line 97, in save
    self.set_mp4()
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/tidal_dl_ng/metadata.py", line 143, in set_mp4
    self.m.tags["\xa9lyr"] = self.lyrics
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/mutagen/mp4/__init__.py", line 372, in __setitem__
    self._render(key, value)
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/mutagen/mp4/__init__.py", line 388, in _render
    return render_func(self, key, value, *render_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/.pyenv/versions/3.11.8/lib/python3.11/site-packages/mutagen/mp4/__init__.py", line 822, in __render_text
    for v in value:
TypeError: 'NoneType' object is not iterable
```

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "/home/eric/Musik", "quality_audio": "HI_RES_LOSSLESS", "quality_video": 1080, "format_album": "Albums/{artist_name}/{album_title}/{track_num} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name}/{track_title}/{track_num} - {track_title}", "format_video": "Videos/{artist_name}/{track_title}", "video_convert_mp4": true, "metadata_cover_dimension": "1280x1280"}
```

**Comment by exislow** [comment]
Thanks you for this report. I have fixed it in: https://github.com/exislow/tidal-dl-ng/releases/tag/v0.8.3
