### ISSUE TITLE
[Bug]  v0.10.1 [ Windows 11 ]

### ISSUE THREAD

**Issue by NikolaZhechev** [exislow/tidal-dl-ng#74]
### What happened?

Version v0.10.1 and it doesn't work on my OS  Windows 11 Home

![Без име](https://github.com/exislow/tidal-dl-ng/assets/42648693/69b46211-41ef-475d-b769-8e654a29c378)

### Version

Windows 11 Home (10.0.22631)

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 683, in <module>
  File "tidal_dl_ng\gui.py", line 676, in gui_activate
  File "tidal_dl_ng\gui.py", line 79, in __init__
  File "tidal_dl_ng\helper\decorator.py", line 19, in __call__
  File "tidal_dl_ng\config.py", line 77, in __init__
  File "tidal_dl_ng\config.py", line 68, in read
  File "tidal_dl_ng\config.py", line 33, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\STARO\\.config\\tidal_dl_ng\\settings.json'
```

### Your settings

```json
Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 683, in <module>
  File "tidal_dl_ng\gui.py", line 676, in gui_activate
  File "tidal_dl_ng\gui.py", line 79, in __init__
  File "tidal_dl_ng\helper\decorator.py", line 19, in __call__
  File "tidal_dl_ng\config.py", line 77, in __init__
  File "tidal_dl_ng\config.py", line 68, in read
  File "tidal_dl_ng\config.py", line 33, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\STARO\\.config\\tidal_dl_ng\\settings.json'
```

**Comment by exislow** [comment]
As the error message says "`Permission denied`". Get your file and app permissions right. It's not a bug of this app. Unfortunately, I cannot help you with Windows. Please google...
